-- MySQL Script generated by MySQL Workbench
-- Sat Jun  7 12:19:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FinanceControl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FinanceControl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FinanceControl` DEFAULT CHARACTER SET utf8 ;
USE `FinanceControl` ;

-- -----------------------------------------------------
-- Table `FinanceControl`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceControl`.`Suppliers` (
  `idSuppliers` INT NOT NULL AUTO_INCREMENT,
  `supplierName` MEDIUMTEXT NOT NULL,
  `supplierCNPJ` VARCHAR(255) NOT NULL,
  `supplierActive` TINYINT NULL,
  `supplierStatus` ENUM('OK', 'Dívida', 'Aberto') NULL,
  `supplierBirth` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `supplierLastActive` DATETIME NULL,
  `supplierObs` VARCHAR(255) NULL,
  `Supplierscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idSuppliers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinanceControl`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceControl`.`Products` (
  `ProductId` INT NOT NULL AUTO_INCREMENT,
  `ProductName` VARCHAR(255) NOT NULL,
  `ProductSalePrice` INT NULL,
  `productInternalId` VARCHAR(45) NULL,
  `productCost` INT NULL,
  `Productscol` VARCHAR(45) NULL,
  UNIQUE INDEX `ProductId_UNIQUE` (`ProductId` ASC) VISIBLE,
  PRIMARY KEY (`ProductId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinanceControl`.`Supplies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceControl`.`Supplies` (
  `supplyID` INT NOT NULL AUTO_INCREMENT,
  `supplyName` VARCHAR(255) NULL,
  `supplyMeasure` VARCHAR(255) NULL,
  `availableAmount` INT NULL,
  `monthlyAmount` INT NULL,
  `pricebyUnit` INT NULL,
  `amountbyUnit` INT NULL,
  PRIMARY KEY (`supplyID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinanceControl`.`Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceControl`.`Sales` (
  `idSalesDay` INT NOT NULL,
  `dateSales` DATE NOT NULL,
  `salesData` JSON NOT NULL,
  PRIMARY KEY (`idSalesDay`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinanceControl`.`suppliesByProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceControl`.`suppliesByProduct` (
  `productFK` INT NOT NULL,
  `qty` INT NULL,
  `supplyFK` INT NULL,
  INDEX `fk_suppliesByProduct_Supplies_idx` (`supplyFK` ASC) VISIBLE,
  INDEX `fk_suppliesByProduct_Products1_idx` (`productFK` ASC) VISIBLE,
  CONSTRAINT `fk_suppliesByProduct_Supplies`
    FOREIGN KEY (`supplyFK`)
    REFERENCES `FinanceControl`.`Supplies` (`supplyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suppliesByProduct_Products1`
    FOREIGN KEY (`productFK`)
    REFERENCES `FinanceControl`.`Products` (`ProductId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
